/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\kveld\Documents\code\game\gb\test\src\sprite\backgroundTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundMapWidth 32
#define backgroundMapHeight 32
#define backgroundMapBank 0

#define backgroundMap backgroundMapPLN0
extern unsigned char backgroundMapPLN0[];
extern unsigned char backgroundMapPLN1[];

/* End of BACKGROUNDMAP.H */
